### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by zacheryph** [biosan/dotfiles#3]
After many months of my current dotfiles barely working, i stopped trying to do _everything_ with nix-darwin/home-manager and accepted that its ok to use both nix/home-manager AND homebrew.

Thank you very much for all the work you'be done on your dotfiles.

**Comment by biosan** [comment]
Thank you very much for your kind words, I'm glad this repo helped you.
Nix/home-manager it's awesome for CLI/terminal stuff even on macOS but for GUI apps it's much simpler to use Homebrew, these kind of apps usually require less configuration and it's ok to handle them manually or with a simple script (terminal apps are usually the exception)
